<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Advice</name>
  <uuid>0e173c07-bcaf-4254-b926-0572953cc477</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
Name is defined 
then
set decision to`Hello { Name }!`;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
